// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef USER_ODB_HXX
#define USER_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "user.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>
#include <odb/view-image.hxx>
#include <odb/view-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // user
  //
  template <>
  struct class_traits< ::user >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::user >
  {
    public:
    typedef ::user object_type;
    typedef ::user* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::uint32_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // user_stat
  //
  template <>
  struct class_traits< ::user_stat >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::user_stat >
  {
    public:
    typedef ::user_stat view_type;
    typedef ::user_stat* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // user
  //
  template <typename A>
  struct query_columns< ::user, id_sqlite, A >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint32_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // login
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    login_type_;

    static const login_type_ login;

    // password
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    password_type_;

    static const password_type_ password;

    // saltUser
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    saltUser_type_;

    static const saltUser_type_ saltUser;

    // saltSession
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    saltSession_type_;

    static const saltSession_type_ saltSession;

    // token
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    token_type_;

    static const token_type_ token;

    // lastConnection
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint32_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    lastConnection_type_;

    static const lastConnection_type_ lastConnection;
  };

  template <typename A>
  const typename query_columns< ::user, id_sqlite, A >::id_type_
  query_columns< ::user, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::user, id_sqlite, A >::login_type_
  query_columns< ::user, id_sqlite, A >::
  login (A::table_name, "\"login\"", 0);

  template <typename A>
  const typename query_columns< ::user, id_sqlite, A >::password_type_
  query_columns< ::user, id_sqlite, A >::
  password (A::table_name, "\"password\"", 0);

  template <typename A>
  const typename query_columns< ::user, id_sqlite, A >::saltUser_type_
  query_columns< ::user, id_sqlite, A >::
  saltUser (A::table_name, "\"saltUser\"", 0);

  template <typename A>
  const typename query_columns< ::user, id_sqlite, A >::saltSession_type_
  query_columns< ::user, id_sqlite, A >::
  saltSession (A::table_name, "\"saltSession\"", 0);

  template <typename A>
  const typename query_columns< ::user, id_sqlite, A >::token_type_
  query_columns< ::user, id_sqlite, A >::
  token (A::table_name, "\"token\"", 0);

  template <typename A>
  const typename query_columns< ::user, id_sqlite, A >::lastConnection_type_
  query_columns< ::user, id_sqlite, A >::
  lastConnection (A::table_name, "\"lastConnection\"", 0);

  template <typename A>
  struct pointer_query_columns< ::user, id_sqlite, A >:
    query_columns< ::user, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::user, id_sqlite >:
    public access::object_traits< ::user >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // m_id
      //
      long long m_id_value;
      bool m_id_null;

      // m_login
      //
      details::buffer m_login_value;
      std::size_t m_login_size;
      bool m_login_null;

      // m_password
      //
      details::buffer m_password_value;
      std::size_t m_password_size;
      bool m_password_null;

      // m_saltUser
      //
      details::buffer m_saltUser_value;
      std::size_t m_saltUser_size;
      bool m_saltUser_null;

      // m_saltSession
      //
      details::buffer m_saltSession_value;
      std::size_t m_saltSession_size;
      bool m_saltSession_null;

      // m_token
      //
      details::buffer m_token_value;
      std::size_t m_token_size;
      bool m_token_null;

      // m_lastConnection
      //
      long long m_lastConnection_value;
      bool m_lastConnection_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::user, id_common >:
    public access::object_traits_impl< ::user, id_sqlite >
  {
  };

  // user_stat
  //
  template <>
  class access::view_traits_impl< ::user_stat, id_sqlite >:
    public access::view_traits< ::user_stat >
  {
    public:
    struct image_type
    {
      // count
      //
      long long count_value;
      bool count_null;

      std::size_t version;
    };

    typedef sqlite::view_statements<view_type> statements_type;

    typedef sqlite::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 1UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);
  };

  template <>
  class access::view_traits_impl< ::user_stat, id_common >:
    public access::view_traits_impl< ::user_stat, id_sqlite >
  {
  };

  // user
  //
  // user_stat
  //
  struct access::view_traits_impl< ::user_stat, id_sqlite >::query_columns:
    odb::pointer_query_columns<
      ::user,
      id_sqlite,
      odb::access::object_traits_impl< ::user, id_sqlite > >
  {
  };
}

#include "user-odb.ixx"

#include <odb/post.hxx>

#endif // USER_ODB_HXX
