// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "user-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/view-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>
#include <odb/sqlite/view-result.hxx>

namespace odb
{
  // user
  //

  struct access::object_traits_impl< ::user, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::user, id_sqlite >::id_type
  access::object_traits_impl< ::user, id_sqlite >::
  id (const id_image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::uint32_t,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::user, id_sqlite >::id_type
  access::object_traits_impl< ::user, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::uint32_t,
          sqlite::id_integer >::set_value (
        id,
        i.m_id_value,
        i.m_id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::user, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // m_id
    //
    t[0UL] = false;

    // m_login
    //
    if (t[1UL])
    {
      i.m_login_value.capacity (i.m_login_size);
      grew = true;
    }

    // m_password
    //
    if (t[2UL])
    {
      i.m_password_value.capacity (i.m_password_size);
      grew = true;
    }

    // m_saltUser
    //
    if (t[3UL])
    {
      i.m_saltUser_value.capacity (i.m_saltUser_size);
      grew = true;
    }

    // m_saltSession
    //
    if (t[4UL])
    {
      i.m_saltSession_value.capacity (i.m_saltSession_size);
      grew = true;
    }

    // m_token
    //
    if (t[5UL])
    {
      i.m_token_value.capacity (i.m_token_size);
      grew = true;
    }

    // m_lastConnection
    //
    t[6UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::user, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // m_id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.m_id_value;
      b[n].is_null = &i.m_id_null;
      n++;
    }

    // m_login
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_login_value.data ();
    b[n].size = &i.m_login_size;
    b[n].capacity = i.m_login_value.capacity ();
    b[n].is_null = &i.m_login_null;
    n++;

    // m_password
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_password_value.data ();
    b[n].size = &i.m_password_size;
    b[n].capacity = i.m_password_value.capacity ();
    b[n].is_null = &i.m_password_null;
    n++;

    // m_saltUser
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_saltUser_value.data ();
    b[n].size = &i.m_saltUser_size;
    b[n].capacity = i.m_saltUser_value.capacity ();
    b[n].is_null = &i.m_saltUser_null;
    n++;

    // m_saltSession
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_saltSession_value.data ();
    b[n].size = &i.m_saltSession_size;
    b[n].capacity = i.m_saltSession_value.capacity ();
    b[n].is_null = &i.m_saltSession_null;
    n++;

    // m_token
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_token_value.data ();
    b[n].size = &i.m_token_size;
    b[n].capacity = i.m_token_value.capacity ();
    b[n].is_null = &i.m_token_null;
    n++;

    // m_lastConnection
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.m_lastConnection_value;
    b[n].is_null = &i.m_lastConnection_null;
    n++;
  }

  void access::object_traits_impl< ::user, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::user, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // m_id
    //
    if (sk == statement_insert)
    {
      ::uint32_t const& v =
        o.m_id;

      bool is_null (false);
      sqlite::value_traits<
          ::uint32_t,
          sqlite::id_integer >::set_image (
        i.m_id_value,
        is_null,
        v);
      i.m_id_null = is_null;
    }

    // m_login
    //
    {
      ::std::string const& v =
        o.m_login;

      bool is_null (false);
      std::size_t cap (i.m_login_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.m_login_value,
        i.m_login_size,
        is_null,
        v);
      i.m_login_null = is_null;
      grew = grew || (cap != i.m_login_value.capacity ());
    }

    // m_password
    //
    {
      ::std::string const& v =
        o.m_password;

      bool is_null (false);
      std::size_t cap (i.m_password_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.m_password_value,
        i.m_password_size,
        is_null,
        v);
      i.m_password_null = is_null;
      grew = grew || (cap != i.m_password_value.capacity ());
    }

    // m_saltUser
    //
    {
      ::std::string const& v =
        o.m_saltUser;

      bool is_null (false);
      std::size_t cap (i.m_saltUser_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.m_saltUser_value,
        i.m_saltUser_size,
        is_null,
        v);
      i.m_saltUser_null = is_null;
      grew = grew || (cap != i.m_saltUser_value.capacity ());
    }

    // m_saltSession
    //
    {
      ::std::string const& v =
        o.m_saltSession;

      bool is_null (false);
      std::size_t cap (i.m_saltSession_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.m_saltSession_value,
        i.m_saltSession_size,
        is_null,
        v);
      i.m_saltSession_null = is_null;
      grew = grew || (cap != i.m_saltSession_value.capacity ());
    }

    // m_token
    //
    {
      ::std::string const& v =
        o.m_token;

      bool is_null (false);
      std::size_t cap (i.m_token_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.m_token_value,
        i.m_token_size,
        is_null,
        v);
      i.m_token_null = is_null;
      grew = grew || (cap != i.m_token_value.capacity ());
    }

    // m_lastConnection
    //
    {
      ::uint32_t const& v =
        o.m_lastConnection;

      bool is_null (false);
      sqlite::value_traits<
          ::uint32_t,
          sqlite::id_integer >::set_image (
        i.m_lastConnection_value,
        is_null,
        v);
      i.m_lastConnection_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::user, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // m_id
    //
    {
      ::uint32_t& v =
        o.m_id;

      sqlite::value_traits<
          ::uint32_t,
          sqlite::id_integer >::set_value (
        v,
        i.m_id_value,
        i.m_id_null);
    }

    // m_login
    //
    {
      ::std::string& v =
        o.m_login;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.m_login_value,
        i.m_login_size,
        i.m_login_null);
    }

    // m_password
    //
    {
      ::std::string& v =
        o.m_password;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.m_password_value,
        i.m_password_size,
        i.m_password_null);
    }

    // m_saltUser
    //
    {
      ::std::string& v =
        o.m_saltUser;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.m_saltUser_value,
        i.m_saltUser_size,
        i.m_saltUser_null);
    }

    // m_saltSession
    //
    {
      ::std::string& v =
        o.m_saltSession;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.m_saltSession_value,
        i.m_saltSession_size,
        i.m_saltSession_null);
    }

    // m_token
    //
    {
      ::std::string& v =
        o.m_token;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.m_token_value,
        i.m_token_size,
        i.m_token_null);
    }

    // m_lastConnection
    //
    {
      ::uint32_t& v =
        o.m_lastConnection;

      sqlite::value_traits<
          ::uint32_t,
          sqlite::id_integer >::set_value (
        v,
        i.m_lastConnection_value,
        i.m_lastConnection_null);
    }
  }

  void access::object_traits_impl< ::user, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          ::uint32_t,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::user, id_sqlite >::persist_statement[] =
  "INSERT INTO \"user\" "
  "(\"id\", "
  "\"login\", "
  "\"password\", "
  "\"saltUser\", "
  "\"saltSession\", "
  "\"token\", "
  "\"lastConnection\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::user, id_sqlite >::find_statement[] =
  "SELECT "
  "\"user\".\"id\", "
  "\"user\".\"login\", "
  "\"user\".\"password\", "
  "\"user\".\"saltUser\", "
  "\"user\".\"saltSession\", "
  "\"user\".\"token\", "
  "\"user\".\"lastConnection\" "
  "FROM \"user\" "
  "WHERE \"user\".\"id\"=?";

  const char access::object_traits_impl< ::user, id_sqlite >::update_statement[] =
  "UPDATE \"user\" "
  "SET "
  "\"login\"=?, "
  "\"password\"=?, "
  "\"saltUser\"=?, "
  "\"saltSession\"=?, "
  "\"token\"=?, "
  "\"lastConnection\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::user, id_sqlite >::erase_statement[] =
  "DELETE FROM \"user\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::user, id_sqlite >::query_statement[] =
  "SELECT "
  "\"user\".\"id\", "
  "\"user\".\"login\", "
  "\"user\".\"password\", "
  "\"user\".\"saltUser\", "
  "\"user\".\"saltSession\", "
  "\"user\".\"token\", "
  "\"user\".\"lastConnection\" "
  "FROM \"user\"";

  const char access::object_traits_impl< ::user, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"user\"";

  const char access::object_traits_impl< ::user, id_sqlite >::table_name[] =
  "\"user\"";

  void access::object_traits_impl< ::user, id_sqlite >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.m_id_null = true;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.m_id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::user, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.m_id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::user, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::user, id_sqlite >::pointer_type
  access::object_traits_impl< ::user, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::user, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::user, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.m_id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::user, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::user, id_sqlite >::object_type >
  access::object_traits_impl< ::user, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::user, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // user_stat
  //

  bool access::view_traits_impl< ::user_stat, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // count
    //
    t[0UL] = false;

    return grew;
  }

  void access::view_traits_impl< ::user_stat, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i)
  {
    using namespace sqlite;

    sqlite::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // count
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.count_value;
    b[n].is_null = &i.count_null;
    n++;
  }

  void access::view_traits_impl< ::user_stat, id_sqlite >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // count
    //
    {
      ::std::size_t& v =
        o.count;

      sqlite::value_traits<
          ::std::size_t,
          sqlite::id_integer >::set_value (
        v,
        i.count_value,
        i.count_null);
    }
  }

  access::view_traits_impl< ::user_stat, id_sqlite >::query_base_type
  access::view_traits_impl< ::user_stat, id_sqlite >::
  query_statement (const query_base_type& q)
  {
    query_base_type r (
      "SELECT "
      "count(\"user\".\"id\") ");

    r += "FROM \"user\"";

    if (!q.empty ())
    {
      r += " ";
      r += q.clause_prefix ();
      r += q;
    }

    return r;
  }

  result< access::view_traits_impl< ::user_stat, id_sqlite >::view_type >
  access::view_traits_impl< ::user_stat, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (query_statement (q));
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        qs.clause (),
        false,
        true,
        qs.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) sqlite::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"user\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"user\" (\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,\n"
                      "  \"login\" TEXT NOT NULL CHECK(login != ''),\n"
                      "  \"password\" TEXT NOT NULL CHECK(password != ''),\n"
                      "  \"saltUser\" TEXT NOT NULL CHECK(saltUser != ''),\n"
                      "  \"saltSession\" TEXT NOT NULL,\n"
                      "  \"token\" TEXT NOT NULL,\n"
                      "  \"lastConnection\" INTEGER NOT NULL)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
