name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.SONAR_REPO_ACCESS_TOKEN }}
          exclude_check:client
          force_language:c++
          std:c++20

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.SONAR_REPO_ACCESS_TOKEN }}
          BRANCH_NAME: 'main'
